### ISSUE TITLE
by Hbase sink  load data into hbase table

### ISSUE THREAD

**Issue by umeshocc** [brockn/flume-hbase-serializer#1]
Hi ,

I am using hbase sink to load data into hbase table .

i have file data like bellow .
"val1,val2" 
Please help to know appropriate RegexHbaseEventSerializer 
sink1.serializer.regex =?

**Comment by brockn** [comment]
Read here:

https://community.cloudera.com/t5/Data-Ingestion-Integration/Flume-org-apache-flume-sink-hbase-RegexHbaseEventSerializer/m-p/20132/highlight/true#M475

but I might also look at Nifi and StreamSets.
